### ISSUE TITLE
WorldGen crash with Binnie's Mods?

### ISSUE THREAD

**Issue by dacrep** [XCompWiz/Mystcraft-Issues#112]
Happens sometimes when generating a New World.
BINNIE-MODS-2.0-PRE12.jar
mystcraft-1.7.10-0.12.0.00.jar

The Problem didnt occurred with mystcraft-1.7.10-0.11.13.00.jar.

[30/6/2015 20:41:47 PM] Description: Exception in server tick loop
[30/6/2015 20:41:47 PM] 
[30/6/2015 20:41:47 PM] java.util.ConcurrentModificationException
[30/6/2015 20:41:47 PM]     at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
[30/6/2015 20:41:47 PM]     at java.util.ArrayList$Itr.next(Unknown Source)
[30/6/2015 20:41:47 PM]     at binnie.extratrees.machines.Lumbermill.getPlankProduct(Lumbermill.java:149)
[30/6/2015 20:41:47 PM]     at binnie.core.genetics.TreeBreedingSystem.calculateArrays(TreeBreedingSystem.java:158)
[30/6/2015 20:41:47 PM]     at binnie.core.genetics.ManagerGenetics.refreshData(ManagerGenetics.java:147)
[30/6/2015 20:41:47 PM]     at binnie.core.genetics.ManagerGenetics.onWorldLoad(ManagerGenetics.java:141)
[30/6/2015 20:41:47 PM]     at cpw.mods.fml.common.eventhandler.ASMEventHandler_398_ManagerGenetics_onWorldLoad_Load.invoke(.dynamic)
[30/6/2015 20:41:47 PM]     at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[30/6/2015 20:41:47 PM]     at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
[30/6/2015 20:41:47 PM]     at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:247)
[30/6/2015 20:41:47 PM]     at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:705)
[30/6/2015 20:41:47 PM]     at com.xcompwiz.mystcraft.world.profiling.InstabilityDataCalculator.stepChunkGeneration(InstabilityDataCalculator.java:336)
[30/6/2015 20:41:47 PM]     at com.xcompwiz.mystcraft.world.profiling.InstabilityDataCalculator.onServerTick(InstabilityDataCalculator.java:180)
[30/6/2015 20:41:47 PM]     at cpw.mods.fml.common.eventhandler.ASMEventHandler_2165_InstabilityDataCalculator_onServerTick_ServerTickEvent.invoke(.dynamic)
[30/6/2015 20:41:47 PM]     at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[30/6/2015 20:41:47 PM]     at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
[30/6/2015 20:41:47 PM]     at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
[30/6/2015 20:41:47 PM]     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
[30/6/2015 20:41:47 PM]     at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
[30/6/2015 20:41:47 PM]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[30/6/2015 20:41:47 PM]     at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[30/6/2015 20:41:47 PM] 
[30/6/2015 20:41:47 PM] 

http://paste.atlauncher.com/view/20e0e235

**Comment by Bogdan-G** [comment]
`forge-1.7.10-10.13.4.1448-1.7.10`
downgrade forge version to 1420/1408/1380 and test run.

**Comment by Tsunayoshi** [comment]
same here on forge-1.7.10-10.13.4.1481-1.7.10.
mystcraft-1.7.10-0.12.0.00

runs without problems at mystcraft-1.7.10-0.11.13.00
(no way I could downgrade at >260 mods without other problems)

**Comment by XCompWiz** [comment]
Concurrent Modification is a thing only the mod with the issue can fix, so Bennie will have to address this. Looks like it was reading and writing to an array at the same time.
