### ISSUE TITLE
Client crash 'Client-Side Storage Missing" (absolutely not caused by accelerated age)

### ISSUE THREAD

**Issue by Robijnvogel** [XCompWiz/Mystcraft-Issues#123]
When connecting to my FTB Infinity 1.8.2 server, my client crashes:
pastebin.com/j7ePD03T
(googling I found this one as well pastebin.com/1Q2uySGx)

I have an accelerated age that has Chunkloaders in it.
This age has run for about a week and has survived several server restarts without trouble.
However, I edited the nbt data of the age and removed the acceleration. This did not help. Then I outright deleted the forcedchunks.dat. This did not help either.
Actually Deleting the whole age altogether did not solve the problem either. (It did change the type of crash though)

Now, however, Mystcraft is, out of the blue, crashing the client of anyone who is trying to connect regardless of which age or place they are in.

What may be the problem though: I have recently installed an AE quantum ring between another Mystcraft age and the overworld that is transporting Thaumcraft Centivis over Thaumic Energistics' Vis Relay Interfaces. I have heard that the Thaumcraft vis relays can derp as a consequence of chunk loading order.

**Comment by XCompWiz** [comment]
The error looks to be caused by the client-side agedata manager not being started properly. I can look into it to try and determine what could cause that.

**Comment by spamenigma** [comment]
Getting the problem here too, so instantly crashing as soon as rejoining the server. Was a new Mystcraft dimension.

http://pastebin.com/UUX8pL49

java.lang.RuntimeException: Client-Side Storage Missing (Attempted as remote)
        at com.xcompwiz.mystcraft.Mystcraft.getStorage(Mystcraft.java:402)
        at com.xcompwiz.mystcraft.world.agedata.AgeData.getAge(AgeData.java:328)
        at com.xcompwiz.mystcraft.world.WorldProviderMyst.func_76572_b(WorldProviderMyst.java:69)
        at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:44)
        at net.minecraft.world.World.finishSetup(World.java:203)
        at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:59)
        at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:238)
        at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
        at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
        at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661)
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
        at net.minecraft.client.main.Main.main(SourceFile:148)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Robijnvogel** [comment]
@XCompWiz would you mind referencing a fix commit or push? Or label this as "1.7 won't fix" or would you please explain why you just closed this issue?
Thank you. :)

**Comment by XCompWiz** [comment]
Ah. I really didn't expect anyone to comment on the change.
Because it's from 1.7.10 and I think it was fixed in the update.

I can't reference a commit or push because there isn't code in this repo.

Hope that answers satisfactorily.

**Comment by Robijnvogel** [comment]
Why is there no code is this repository?!? Jk, man. I just totally forgot that this repo was just for issues. My issue report was from two years ago. Go figure. :D

So I guess this won't get fixed for the 1.7.10 version, then? Which I could obviously understand.
