### ISSUE TITLE
Mystcraft getting world OOM crash

### ISSUE THREAD

**Issue by DarkholmeTenk** [XCompWiz/Mystcraft-Issues#131]
Lovely stuff. User says this issue happens with 4gb of memory allocated to server.

``` java
java.lang.OutOfMemoryError: Java heap space
at net.minecraft.nbt.NBTTagIntArray.func_152446_a(NBTTagIntArray.java:35)
at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:398)
at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:52)
at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:398)
at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:52)
at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:398)
at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:52)
at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:170)
at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:125)
at net.minecraft.nbt.CompressedStreamTools.func_74796_a(CompressedStreamTools.java:34)
at net.minecraft.world.storage.MapStorage.func_75742_a(SourceFile:45)
at com.xcompwiz.mystcraft.world.AgeController.getChunkProfiler(AgeController.java:506)
at com.xcompwiz.mystcraft.world.AgeController.registerDebugInfo(AgeController.java:251)
at com.xcompwiz.mystcraft.core.MystcraftEventHandler.handleWorldLoadEvent(MystcraftEventHandler.java:106)
at cpw.mods.fml.common.eventhandler.ASMEventHandler_300_MystcraftEventHandler_handleWorldLoadEvent_Load.invoke(.dynamic)
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:247)
at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:705)
at io.darkcraft.darkcore.mod.helpers.WorldHelper.getWorldServer(WorldHelper.java:35)
at io.darkcraft.darkcore.mod.helpers.WorldHelper.getWorld(WorldHelper.java:27)
at io.darkcraft.darkcore.mod.helpers.WorldHelper.getDimensionName(WorldHelper.java:61)
at tardis.common.tileents.CoreTileEntity.writeTransmittableOnly(CoreTileEntity.java:1658)
at io.darkcraft.darkcore.mod.abstracts.AbstractTileEntity.func_145844_m(AbstractTileEntity.java:73)
at net.minecraft.server.management.PlayerManager$PlayerInstance.func_151252_a(PlayerManager.java:591)
at net.minecraft.server.management.PlayerManager$PlayerInstance.func_73254_a(PlayerManager.java:576)
at net.minecraft.server.management.PlayerManager.func_72693_b(PlayerManager.java:67)
at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:185)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
```

I've asked for a memory profile, but still waiting on a response :)

Edit: I've mitigated the problem on my end by caching names by dimension id rather than trying to get them from the world each time. Should fix the problem, waiting to hear from the reporting user.

**Comment by XCompWiz** [comment]
A memory profile should help, ya.
I'd be surprised if the chunk profiling data is that large alone, but it's possible it's not getting unloaded and loading lots of them causes an issue. I think that the map data system has that problem sometimes.

**Comment by handicraftsman** [comment]
4gb ram... out of memory... wtf?

**Comment by adamcogx** [comment]
That's what I thought.  I was running a server in 2GB of RAM previously, and I'm the only one on the server (it's my personal server)
