### ISSUE TITLE
agedata file not created

### ISSUE THREAD

**Issue by plumarr** [XCompWiz/Mystcraft-Issues#159]
Hello,

I'm currently hosting a small server with FTB Infinity evolved 2.5.0 (Mystcraft version 0.12.3.01) and I'm encountering an issue with mystcraft.

Each time we create a world with a liking book, the file agedate isn't created. So, the world work fine until the next server reboot but can't be used after that.

Looking in the log file, we got NPE at world creation and each time a player enter or leave the world (see attached log file for more details) : 
`[19:21:41] [Server thread/ERROR] [FML/]: Exception caught during firing event cpw.mods.fml.common.gameevent.PlayerEvent$PlayerChangedDimensionEvent@52a2ef6a:
java.lang.NullPointerException
    at net.minecraft.nbt.NBTTagList.func_74742_a(NBTTagList.java:85) ~[dq.class:?]
    at com.xcompwiz.mystcraft.world.agedata.AgeData.func_76187_b(AgeData.java:298) ~[AgeData.class:?]
    at com.xcompwiz.mystcraft.network.packet.MPacketAgeData.getDataPacket(MPacketAgeData.java:30) ~[MPacketAgeData.class:?]
    at com.xcompwiz.mystcraft.network.NetworkUtils.sendAgeData(NetworkUtils.java:101) ~[NetworkUtils.class:?]
...`

Could-you help me solve this issue ?

[fml-server-latest.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/276558/fml-server-latest.txt)

**Comment by XCompWiz** [comment]
Curious.

How are you creating these descriptive books?  What are you naming them?
