### ISSUE TITLE
Mystcraft API crash

### ISSUE THREAD

**Issue by Keyarose** [XCompWiz/Mystcraft-Issues#162]
The game crashes when generating a new world, does not happen when opening a preexisting world. Started happening after updating DragonAPI

Crash log: http://pastebin.com/F3xJeKig

Mystcraft version: 0.12.3.02
DragonAPI V14d

ReikaKalseki/Reika_Mods_Issues#947

**Comment by ReikaKalseki** [comment]
I can confirm it happens for me too, well past having logged into a world. And this *is* a pre-existing world.

java.lang.NullPointerException
	at com.xcompwiz.mystcraft.api.impl.linking.DimensionAPIDelegate.isMystcraftAge(DimensionAPIDelegate.java:16) ~[DimensionAPIDelegate.class:?]
	at com.xcompwiz.mystcraft.api.impl.linking.DimensionAPIWrapper.isMystcraftAge(DimensionAPIWrapper.java:22) ~[DimensionAPIWrapper.class:?]
	at <PROFILE NAME>.DragonAPI.ModInteract.DeepInteract.<PROFILE NAME>MystcraftHelper.isMystAge(<PROFILE NAME>MystcraftHelper.java:113) ~[<PROFILE NAME>MystcraftHelper.class:?]
	at <PROFILE NAME>.ChromatiCraft.World.PylonGenerator.canGenerateIn(PylonGenerator.java:301) ~[PylonGenerator.class:?]
	at <PROFILE NAME>.ChromatiCraft.Auxiliary.Render.ChromaOverlays.renderHUD(ChromaOverlays.java:199) ~[ChromaOverlays.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1152_ChromaOverlays_renderHUD_Pre.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]

**Comment by plaguewolf** [comment]
i am also having this problem upon updating today, should i roll back mystcraft, and if so, to which version?

`Description: Exception getting block type in world

java.lang.NullPointerException: Exception getting block type in world
	at com.xcompwiz.mystcraft.api.impl.linking.DimensionAPIDelegate.isMystcraftAge(DimensionAPIDelegate.java:16)
	at com.xcompwiz.mystcraft.api.impl.linking.DimensionAPIWrapper.isMystcraftAge(DimensionAPIWrapper.java:22)
	at Reika.DragonAPI.ModInteract.DeepInteract.ReikaMystcraftHelper.isMystAge(ReikaMystcraftHelper.java:113)
	at Reika.ChromatiCraft.World.PylonGenerator.canGenerateIn(PylonGenerator.java:301)
	at Reika.ChromatiCraft.World.PylonGenerator.generate(PylonGenerator.java:272)
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
	at Reika.ChromatiCraft.Auxiliary.ChromaAux.interceptChunkPopulation(ChromaAux.java:88)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1045)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at net.minecraft.world.World.func_147437_c(World.java:365)
	at net.minecraft.world.World.func_147474_b(World.java:329)
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:71)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:749)
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:715)
	at net.minecraft.world.World.<init>(World.java:260)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:14)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:65)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)`

`Stacktrace:
	at com.xcompwiz.mystcraft.api.impl.linking.DimensionAPIDelegate.isMystcraftAge(DimensionAPIDelegate.java:16)
	at com.xcompwiz.mystcraft.api.impl.linking.DimensionAPIWrapper.isMystcraftAge(DimensionAPIWrapper.java:22)
	at Reika.DragonAPI.ModInteract.DeepInteract.ReikaMystcraftHelper.isMystAge(ReikaMystcraftHelper.java:113)
	at Reika.ChromatiCraft.World.PylonGenerator.canGenerateIn(PylonGenerator.java:301)
	at Reika.ChromatiCraft.World.PylonGenerator.generate(PylonGenerator.java:272)
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
	at Reika.ChromatiCraft.Auxiliary.ChromaAux.interceptChunkPopulation(ChromaAux.java:88)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1045)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147439_a(World.java:345)`

tail end of forge log:

`[17:29:56] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception getting block type in world
	at net.minecraft.world.World.<init>(World.java:275) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97) ~[mt.class:?]
	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:14) ~[mm.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:65) ~[bsx.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92) ~[bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
Caused by: java.lang.NullPointerException
	at com.xcompwiz.mystcraft.api.impl.linking.DimensionAPIDelegate.isMystcraftAge(DimensionAPIDelegate.java:16) ~[DimensionAPIDelegate.class:?]
	at com.xcompwiz.mystcraft.api.impl.linking.DimensionAPIWrapper.isMystcraftAge(DimensionAPIWrapper.java:22) ~[DimensionAPIWrapper.class:?]
	at Reika.DragonAPI.ModInteract.DeepInteract.ReikaMystcraftHelper.isMystAge(ReikaMystcraftHelper.java:113) ~[ReikaMystcraftHelper.class:?]
	at Reika.ChromatiCraft.World.PylonGenerator.canGenerateIn(PylonGenerator.java:301) ~[PylonGenerator.class:?]
	at Reika.ChromatiCraft.World.PylonGenerator.generate(PylonGenerator.java:272) ~[PylonGenerator.class:?]
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) ~[GameRegistry.class:?]
	at Reika.ChromatiCraft.Auxiliary.ChromaAux.interceptChunkPopulation(ChromaAux.java:88) ~[ChromaAux.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) ~[ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1045) ~[apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) ~[ahb.class:?]
	at net.minecraft.world.World.func_147437_c(World.java:365) ~[ahb.class:?]
	at net.minecraft.world.World.func_147474_b(World.java:329) ~[ahb.class:?]
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:71) ~[aqo.class:?]
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:749) ~[mt.class:?]
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:715) ~[mt.class:?]
	at net.minecraft.world.World.<init>(World.java:260) ~[ahb.class:?]`

**Comment by bookerthegeek** [comment]
You would need to roll back ReikaKalseki mods untill mystcraft or dragonAPI update.

**Comment by plaguewolf** [comment]
ahh, right, cause he changed from reflection to myst API. shiiii....

nah, i'll just pull myst until it gets fixed, no offense reika, but your update reminder thingy is obnoxious.

**Comment by ReikaKalseki** [comment]
If there is no resolution from the MystCraft side, I may just go back to reflection.

**Comment by bookerthegeek** [comment]
I'd give him a couple days.  😉

**Comment by plaguewolf** [comment]
i hate to beat a dead hores... but is there any resolution to this issue?

or at the very least, some way to download 14c mods, ReikaKalseki?

**Comment by KosmosPrime** [comment]
Given that the registeredDims field is public, you can just put this in your class initializer:
`if (Mystcraft.registeredDims == null) {
      Mystcraft.registeredDims = new ArrayList();
    }`

**Comment by ReikaKalseki** [comment]
I already moved back to reflection for v15.

**Comment by XCompWiz** [comment]
Sorry for the really long delay to getting to this issue.

@ReikaKalseki, at what point in execution were you calling this function?
If i understand you correctly, it only occurred on a client connecting to a remote server, correct?  That would mean you managed to ask if a dimension was a Mystcraft age before the client got the list of registered dimensions from the server.  The list is sent as soon as the client connection is opened, though, so just delaying the query should be enough.

**Comment by ReikaKalseki** [comment]
This was in the render loop - note the last three lines of the stacktrace above - and I have a feeling it might be a sidedness issue as the serverside generator has never been reported to have any issues.

Basically, the Pylon Compass overlay HUD (shown below) needs to know if pylons can generate in the current dimension, to avoid wasting CPU time running the renderer. This works fine...unless it was a MystCraft age, whereupon that condition becomes dependent on the page presence. Serverside worked fine, since the generation went without issues. Clientside...not so much.

There is nothing I can do to "delay" the request. I have no way of knowing when the data has been received, and the only API hook is "isMystAge", which crashes.

Also, when using contains(), a HashSet is far superior to any form of list, as contains() requires iteration for lists, which on worlds with 40+ ages (like my server) is far slower.

HUD:
![](http://i.imgur.com/KPLSnPM.png)

**Comment by XCompWiz** [comment]
Hmmm...  Render tick should be late enough.  I'll have to look into any delays for getting this list.  I was pretty sure I'd fixed it so that it would arrive ahead of login.  I wouldn't expect the render tick to happen ahead of that.

> Also, when using contains(), a HashSet is far superior to any form of list
Of course.  I don't recall if the ordered property is required for my registered dims, though.  I'm pretty sure it used to be, at least.  Either way, if it's not required I should be able to change it.  Even still, I expect it's a minor impact at most unless you are calling this function constantly.

**Comment by ReikaKalseki** [comment]
> unless you are calling this function constantly.

Like in the render loop? ![](http://i.imgur.com/xqhgCOk.png)

**Comment by XCompWiz** [comment]
Surely the "is dimension valid" check doesn't need to happen every tick?  If you are going to criticize the lack of optimization in my check function I'd expect you would consider optimizing your own? :P

**Comment by ReikaKalseki** [comment]
> Surely the "is dimension valid" check doesn't need to happen every tick? If you are going to criticize the lack of optimization in my check function I'd expect you would consider optimizing your own?

How else could I do it? This is in the render loop, and in theory the validity of a dimension can change with time (for example player A on a server where admin B has just reloaded a config to toggle superflat generation), which prevents accurate caching (which would be little different than the current interfacing code anyways, as it would still amount to a cache lookup).

Even if not in the render loop, this is also called on worldgen by all my generators whose runnability changes in MystCraft dimensions, as well as several blocks' randomTick behavior (Rainbow Leaves being the most obvious example).

**Comment by XCompWiz** [comment]
Is it possible for the admin to reload the config while the game is running?  How would that propagate to the client?  Couldn't you clear any cached values at the point where it could change?  I assume this has to be your own system if the configs can change at runtime.  You can also detect when a player changes dimension and check then to see if they are in a dimension which can have pylons.
Being little different interface wise just means it's easier for you to do. :)

I've already changed it to a set, as I said I would. My only point is you were complaining about my less than optimal contains check and apparently doing this as an optimization when you could do it more optimally.
Really, I'm just making an equivalent point on the optimization remark, particularly how you presented it.  "Is this intentionally an ArrayList?  Wouldn't it be more efficient as a HashSet?" would have been excellent feedback and I would have thanked you for spotting it.  Presenting it as if it would somehow be a revelation (rather than just code developed over several years changing in nature) just comes across as somewhat arrogant. :)  I just hope I've made my point.  I don't believe you intended to be offensive, but it was easiest to exemplify this way.

I do think my suggestions may be useful to you, particularly if you are concerned for the speed of the render code.  You can also ignore them. :)
----
Anyway, the reason this is still open is I need to check the timings of my list arrival.  I don't want to return a false value if the list has yet to arrive, but I also shouldn't simply crash out.  I might need to make it so that the API call can throw an exception in extreme cases, but it really shouldn't be possible to get there.
