### ISSUE TITLE
Crash when attempting to use Writing Desk

### ISSUE THREAD

**Issue by Starwind65** [XCompWiz/Mystcraft-Issues#168]
Just built a writing desk and when I click on it to use it Minecraft crashes.

[crash-2016-08-09_22.55.27-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/410465/crash-2016-08-09_22.55.27-server.txt)

**Comment by XCompWiz** [comment]
Odd. I had no issues with the desk in testing so until I can get home to look at the code I can't tell you what went wrong.
I did rewrite the GUI init code for the latest build, so that might have something to do with it.

As a random thought, try clicking the other block of the desk (since it's two blocks).  I may not have handled that correctly in the update and consistently clicked on the "working" block when testing it.

**Comment by Starwind65** [comment]
Well I tested your random thought, the error and crash is only occurring when I click on the right side of the desk. The left side works correctly.

**Comment by Starwind65** [comment]
Ok took it one step further with the desk. Made the backboard and it also caused crashes, this time on both left and right sides. The other blocks had no problems.

**Comment by Starwind65** [comment]
Sorry accidentally hit close when I commented. Also checked out the backboard of the desk and it also errors when clicked but on both sides.

**Comment by Gamerbolts** [comment]
Just had this same issue. I checked my logs and this came up

[01:30:06] [Server thread/WARN]: Failed to handle packet for /97.90.243.137:64309
java.lang.NullPointerException
	at com.xcompwiz.mystcraft.inventory.ContainerWritingDesk.<init>(ContainerWritingDesk.java:77) ~[ContainerWritingDesk.class:?]
	at com.xcompwiz.mystcraft.inventory.GuiHandler.getServerGuiElement(GuiHandler.java:52) ~[GuiHandler.class:?]
	at cpw.mods.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:243) ~[NetworkRegistry.class:?]
	at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:75) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(Unknown Source) ~[yz.class:?]
	at com.xcompwiz.mystcraft.block.BlockWritingDesk.func_149727_a(BlockWritingDesk.java:151) ~[BlockWritingDesk.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source) ~[mx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) ~[nh.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at fastcraft.at.a(F:978) [fastcraft-1.23.jar:?]
	at fastcraft.H.aq(F:36) [fastcraft-1.23.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

**Comment by sirrus233** [comment]
I can confirm this issue as well. The user behavior triggering the crash is definitely clicking on the right-hand side of the desk (Block ID 1480)

**Comment by XCompWiz** [comment]
Thanks! I know what happened, then. I'll fix it as soon as I can.

**Comment by HimitsuYami** [comment]
I'm also having an issue trying to use the writing desk, i haven't tested if it's just the one side yet but my crash report says something about Ticking memory connection
[crash-2016-08-16_15.50.40-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/421247/crash-2016-08-16_15.50.40-server.txt)

**Comment by V3XT** [comment]
I have the same issue. The problem also occurs if I click on the writing desk backboard. I guess we'll just have to be careful about it until a fix is released.

**Comment by XCompWiz** [comment]
Ya, just the one block works.  I've not had any time to work on Mystcraft since this was reported, though. It's the first thing on my list when I do. :)

**Comment by jsaggers** [comment]
I can also confirm that right clicking on a writing desk crash my game with a ticking memory error.
[crash-2016-11-28_18.54.49-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/615673/crash-2016-11-28_18.54.49-server.txt)

**Comment by XCompWiz** [comment]
I did a sneaky build last night. Fixed there. :)

**Comment by 12224687** [comment]
so how exactly do you fix the problem

**Comment by 12224687** [comment]
im going to leave my crash  here

The game crashed whilst rendering screen
The game crashed whilst rendering screen
Error: java.lang.NullPointerException

**Comment by XCompWiz** [comment]
You update to the build I uploaded onto CurseForge 2 days ago. :)

**Comment by 12224687** [comment]
thx
