### ISSUE TITLE
1.11.2 - Mystcraft calls PlayerChunkMap.removePlayer when the player is already removed when moving player between dimensions

### ISSUE THREAD

**Issue by Barteks2x** [XCompWiz/Mystcraft-Issues#181]
This happens to silently just work in vanilla, but because of the specific implementation details of cubic chunks it needs special check to make it work, this is the message my mod currently produces, with a stacktrace:
```

16:08:21 | game |   | info | [14:08:21] [Server thread/WARN] [cubicchunks]: ****************************************
16:08:21 | game |   | info | [14:08:21] [Server thread/WARN] [cubicchunks]: * PlayerCubeMap#removePlayer got called when there is no player in this world! Things may break!
16:08:21 | game |   | info | [14:08:21] [Server thread/WARN] [cubicchunks]: *  at cubicchunks.server.PlayerCubeMap.func_72695_c(PlayerCubeMap.java:451)
16:08:21 | game |   | info | [14:08:21] [Server thread/WARN] [cubicchunks]: *  at net.minecraft.server.management.PlayerList.func_72375_a(PlayerList.java:282)
16:08:21 | game |   | info | [14:08:21] [Server thread/WARN] [cubicchunks]: *  at com.xcompwiz.mystcraft.linking.LinkController.teleportEntity(LinkController.java:128)
16:08:21 | game |   | info | [14:08:21] [Server thread/WARN] [cubicchunks]: *  at com.xcompwiz.mystcraft.linking.LinkController.travelEntity(LinkController.java:64)
16:08:21 | game |   | info | [14:08:21] [Server thread/WARN] [cubicchunks]: *  at com.xcompwiz.mystcraft.item.ItemLinking.activate(ItemLinking.java:86)
16:08:21 | game |   | info | [14:08:21] [Server thread/WARN] [cubicchunks]: *  at com.xcompwiz.mystcraft.item.ItemAgebook.activate(ItemAgebook.java:124)...
16:08:21 | game |   | info | [14:08:21] [Server thread/WARN] [cubicchunks]: *  at com.xcompwiz.mystcraft.tileentity.TileEntityBookRotateable.link(TileEntityBookRotateable.java:53)
16:08:21 | game |   | info | [14:08:21] [Server thread/WARN] [cubicchunks]: *  at com.xcompwiz.mystcraft.inventory.ContainerBook.processMessage(ContainerBook.java:298)
16:08:21 | game |   | info | [14:08:21] [Server thread/WARN] [cubicchunks]: ****************************************
```

This could also potentially cause issues with sponge but I didn't test it.

I didn't look at the decompiled code, but it seems similar to issue galacticraft had https://github.com/micdoodle8/Galacticraft/issues/2832.

**Comment by HellFirePvP** [comment]
Should be adressed as of next version. The duplicate call to remove the entity got removed.
