### ISSUE TITLE
Crash when disabling background profiling with OpenTerrainControl

### ISSUE THREAD

**Issue by Katrix-** [XCompWiz/Mystcraft-Issues#213]
When disabling background profiling with OpenTerrainControl, it crashes as soon as it gets to the main menu. Unsure if this is something I should report here or there.

Stacktrace:
`
java.lang.NullPointerException: Ticking memory connection
	at com.khorn.terraincontrol.forge.events.PlayerTracker.SendWorldAndBiomeConfigs(PlayerTracker.java:70)
	at com.khorn.terraincontrol.forge.events.PlayerTracker.onConnectionCreated(PlayerTracker.java:35)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_976_PlayerTracker_onConnectionCreated_ServerConnectionFromClientEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:259)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:211)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.khorn.terraincontrol.forge.events.PlayerTracker.SendWorldAndBiomeConfigs(PlayerTracker.java:70)
	at com.khorn.terraincontrol.forge.events.PlayerTracker.onConnectionCreated(PlayerTracker.java:35)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_976_PlayerTracker_onConnectionCreated_ServerConnectionFromClientEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:259)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:211)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@3624c52f
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by HellFirePvP** [comment]
I'll dig into it and see if disabling the profiling could lead to missing data...

**Comment by XCompWiz** [comment]
Is this still happening?
