### ISSUE TITLE
[0.13.4.02] Crashes server upon loading - Minecraft 1.12.2

### ISSUE THREAD

**Issue by renadi** [XCompWiz/Mystcraft-Issues#236]
I have a hosted server, after adding this mod it crashes with the following message before it finishes loading.
Single player seems to work except for me needing to figure out how to increase my FPS.

```
Time: 5/22/18 6:49 AM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: com.xcompwiz.mystcraft.api.symbol.IAgeSymbol.getLocalizedName()Ljava/lang/String;
	at com.xcompwiz.mystcraft.page.SortingUtils$ComparatorSymbolAlphabetical.compare(SortingUtils.java:69)
	at com.xcompwiz.mystcraft.page.SortingUtils$ComparatorSymbolAlphabetical.compare(SortingUtils.java:61)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:234)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at com.xcompwiz.mystcraft.item.ItemPage.func_150895_a(ItemPage.java:63)
	at crafttweaker.mc1120.item.MCItemUtils.createItemList(MCItemUtils.java:38)
	at crafttweaker.mc1120.brackets.BracketHandlerItem.rebuildItemRegistry(BracketHandlerItem.java:63)
	at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:47)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_430_CommonEventHandler_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:750)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:622)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by Darkmega18** [comment]
ok, yeah, this is what I got just now. good to know it's been gotten.

**Comment by HellFirePvP** [comment]
Version 0.13.4.03 that fixed this is released. Closing the issue~
