### ISSUE TITLE
[1.12.2-0.13.4.03] Crashes server upon starting(with tinker I/O)

### ISSUE THREAD

**Issue by limesnow** [XCompWiz/Mystcraft-Issues#245]
I have a hosted server, after adding this mod it crashes  before it finishes loading.
When mystcraft and tinkerio combine it will crash.

Single player seems to work.

MOD
- Forge-1.12.2-14.23.3.2698-universal
- Mantle-1.12-1.3.2.24
- TConstruct-1.12.2-2.10.0.81
- RedstoneFlux-1.12-2.0.2.3-universal
- tinker_io-1.12.2-release 2.6.1

The message at crash is as follows.
~~~
Time: 18/05/31 18:52
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.xcompwiz.mystcraft.symbol.modifiers.SymbolBlock.getSymbolIdentifier(SymbolBlock.java:33)
	at com.xcompwiz.mystcraft.symbol.modifiers.SymbolBlock.<init>(SymbolBlock.java:25)
	at com.xcompwiz.mystcraft.data.ModSymbolsModifiers$BlockModifierContainerObject.create(ModSymbolsModifiers.java:45)
	at com.xcompwiz.mystcraft.data.ModSymbolsModifiers$BlockModifierContainerObject.create(ModSymbolsModifiers.java:55)
	at com.xcompwiz.mystcraft.data.ModSymbolsFluids.modsLoaded(ModSymbolsFluids.java:57)
	at com.xcompwiz.mystcraft.data.ModRegistryPrimer.onRegistryBiomes(ModRegistryPrimer.java:69)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_59_ModRegistryPrimer_onRegistryBiomes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:750)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)
~~~

**Comment by CommYutzy** [comment]
Same exact error on mine today when I updated all my mods, removing mystcraft fixes it. https://pastebin.com/hsY7ciPT

**Comment by Jkosio23** [comment]
well of course removing mystcraft would fix this mystcraft based error, but even if its mystcraft based, it might not be mystcraft caused

**Comment by Jkosio23** [comment]
also experiencing the same exact error here

**Comment by Jkosio23** [comment]
nope, it was in the pack to begin with, and we felt it was better to have mystcraft after so long of not having it updated rather than a slightly neat tinker's addon

**Comment by CreeperFace00** [comment]
Experiencing the same crash here too

**Comment by jcettison** [comment]
Also experiencing this crash.

**Comment by XCompWiz** [comment]
Looks like an issue with fluid symbol generation. Specifically, Mystcraft asks a fluid block for the meta state at which is it full, and then asks for the block state for that meta. Seems in this case that the resultant blockstate is either null or otherwise weird.
Will need more investigation, but I can add some null catching for the next build at least.

**Comment by XCompWiz** [comment]
Glad to hear it! :D
There may be some fluids which don't get symbols. In that case, check the logs for a message during startup about the fluid reporting bad information.
