### ISSUE TITLE
[1.12.2] CME when picking up pages in writing desk ui.

### ISSUE THREAD

**Issue by ErdrickXLII** [XCompWiz/Mystcraft-Issues#247]
Very occasionally (but still twice in about a half-hour) when I pick up a page from the left side of the writing desk ui (from a folder, not the copied page output slot or my inventory) I get:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-0.12-82-core.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.1.7.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 5/31/18 3:21 PM
Description: Ticking player

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$EntryIterator.next(Unknown Source)
	at java.util.HashMap$EntryIterator.next(Unknown Source)
	at java.util.AbstractCollection.containsAll(Unknown Source)
	at java.util.AbstractSet.equals(Unknown Source)
	at java.util.Objects.equals(Unknown Source)
	at net.minecraft.nbt.NBTTagCompound.equals(NBTTagCompound.java:459)
	at java.util.Objects.equals(Unknown Source)
	at java.util.HashMap$Node.equals(Unknown Source)
	at java.util.HashMap$EntrySet.contains(Unknown Source)
	at java.util.AbstractCollection.containsAll(Unknown Source)
	at java.util.AbstractSet.equals(Unknown Source)
	at java.util.Objects.equals(Unknown Source)
	at net.minecraft.nbt.NBTTagCompound.equals(NBTTagCompound.java:459)
	at net.minecraft.item.ItemStack.func_77959_d(ItemStack.java:462)
	at net.minecraft.item.ItemStack.func_77989_b(ItemStack.java:438)
	at com.xcompwiz.mystcraft.inventory.ContainerWritingDesk.func_75142_b(ContainerWritingDesk.java:165)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:324)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:642)
	at net.minecraft.world.World.func_72939_s(World.java:1731)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

**Comment by XCompWiz** [comment]
Sounds like two threads interacting with the same item at the same time. I can look into it. :) Thanks for reporting it!

**Comment by MarshTheBacca** [comment]
Any news on this bug? It's making writing ages frustrating as it happens every few pages you print.

**Comment by XCompWiz** [comment]
It only seems to happen when picking up and/or placing pages into the portfolios or folders on the left section of the desk. I haven't seen it happen during normal writing.  Still testing to determine the exact cause and how to deal with it.

**Comment by XCompWiz** [comment]
Pretty sure I must have fixed this when i did the inventory fixes before. Would be good if someone could verify it.
I've not been able to reproduce the issue since.

**Comment by MarshTheBacca** [comment]
I'll update to the latest version and pick up a few pages in the inventory. The crash was happening aswell when I picked up the written page from the right side of the UI, just letting you know that.

**Comment by XCompWiz** [comment]
Good to know, thanks. :) Please do let me know.

**Comment by ErdrickXLII** [comment]
I picked up pages and moved them around and picked them back up again for about an hour and it didn't crash, so maybe it's fixed?

**Comment by MarshTheBacca** [comment]
Oh sorry i forgot to update you. Yea i agree the issue is fixed, i've written about 15 more ages and i've not once had the crash.
