### ISSUE TITLE
[1.12.2-0.13.4.03] Game crash when generating ages with Twilight Forest mod

### ISSUE THREAD

**Issue by Nawor3565** [XCompWiz/Mystcraft-Issues#251]
There seems to be some incompatibilities between this mod and Twilight Forest [ver. 1.12.2-3.7.424]. When I generate a random age, there's a chance the game will crash, and from reading the error it seems to be a problem with TF. Here's the crash log:

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.6.0.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.22.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.8.2-1.12.2-anarchy.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 6/4/18 4:08 PM
Description: Exception ticking world

java.lang.RuntimeException: Biome [twilightforest:highlands_center] threw an error while populating chunk.
	at com.xcompwiz.mystcraft.world.ChunkProviderMyst.func_185931_b(ChunkProviderMyst.java:138)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1017)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.world.World.func_72964_e(World.java:309)
	at net.minecraft.world.World.func_175726_f(World.java:304)
	at net.minecraft.world.World.func_180495_p(World.java:910)
	at com.xcompwiz.mystcraft.world.gen.feature.WorldGenLakesAdv.doGeneration(WorldGenLakesAdv.java:75)
	at com.xcompwiz.mystcraft.world.gen.feature.WorldGeneratorAdv.func_180709_b(WorldGeneratorAdv.java:32)
	at com.xcompwiz.mystcraft.symbol.symbols.SymbolLakesSurface$Populator.populate(SymbolLakesSurface.java:55)
	at com.xcompwiz.mystcraft.world.AgeController.populate(AgeController.java:569)
	at com.xcompwiz.mystcraft.world.ChunkProviderMyst.func_185931_b(ChunkProviderMyst.java:143)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1017)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at com.xcompwiz.mystcraft.world.AgeController.expandChunkProfile(AgeController.java:345)
	at com.xcompwiz.mystcraft.world.AgeController.updateProfiledInstability(AgeController.java:322)
	at com.xcompwiz.mystcraft.world.AgeController.getInstabilityScore(AgeController.java:297)
	at com.xcompwiz.mystcraft.instability.InstabilityController.validate(InstabilityController.java:84)
	at com.xcompwiz.mystcraft.instability.InstabilityController.tick(InstabilityController.java:138)
	at com.xcompwiz.mystcraft.world.AgeController.tickBlocksAndAmbiance(AgeController.java:581)
	at com.xcompwiz.mystcraft.world.WorldProviderMyst.canDoLightning(WorldProviderMyst.java:308)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:403)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at twilightforest.world.TFGenWitchHut.generateTinyHut(TFGenWitchHut.java:180)
	at twilightforest.world.TFGenWitchHut.func_180709_b(TFGenWitchHut.java:20)
	at twilightforest.biomes.TFBiomeDecorator.func_150513_a(TFBiomeDecorator.java:102)
	at net.minecraft.world.biome.BiomeDecorator.func_180292_a(BiomeDecorator.java:88)
	at twilightforest.biomes.TFBiomeDecorator.func_180292_a(TFBiomeDecorator.java:91)
	at net.minecraft.world.biome.Biome.func_180624_a(Biome.java:225)
	at com.xcompwiz.mystcraft.world.biome.BiomeWrapperMyst.func_180624_a(BiomeWrapperMyst.java:169)
	at com.xcompwiz.mystcraft.world.ChunkProviderMyst.func_185931_b(ChunkProviderMyst.java:136)
	... 28 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.xcompwiz.mystcraft.world.ChunkProviderMyst.func_185931_b(ChunkProviderMyst.java:138)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1017)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.world.World.func_72964_e(World.java:309)
	at net.minecraft.world.World.func_175726_f(World.java:304)
	at net.minecraft.world.World.func_180495_p(World.java:910)
	at com.xcompwiz.mystcraft.world.gen.feature.WorldGenLakesAdv.doGeneration(WorldGenLakesAdv.java:75)
	at com.xcompwiz.mystcraft.world.gen.feature.WorldGeneratorAdv.func_180709_b(WorldGeneratorAdv.java:32)
	at com.xcompwiz.mystcraft.symbol.symbols.SymbolLakesSurface$Populator.populate(SymbolLakesSurface.java:55)
	at com.xcompwiz.mystcraft.world.AgeController.populate(AgeController.java:569)
	at com.xcompwiz.mystcraft.world.ChunkProviderMyst.func_185931_b(ChunkProviderMyst.java:143)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1017)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at com.xcompwiz.mystcraft.world.AgeController.expandChunkProfile(AgeController.java:345)
	at com.xcompwiz.mystcraft.world.AgeController.updateProfiledInstability(AgeController.java:322)
	at com.xcompwiz.mystcraft.world.AgeController.getInstabilityScore(AgeController.java:297)
	at com.xcompwiz.mystcraft.instability.InstabilityController.validate(InstabilityController.java:84)
	at com.xcompwiz.mystcraft.instability.InstabilityController.tick(InstabilityController.java:138)
	at com.xcompwiz.mystcraft.world.AgeController.tickBlocksAndAmbiance(AgeController.java:581)
	at com.xcompwiz.mystcraft.world.WorldProviderMyst.canDoLightning(WorldProviderMyst.java:308)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:403)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)

-- Affected level --
Details:
	Level name: Copy of Skylands (NEW)
	All players: 1 total; [EntityPlayerMP['Nawor3565'/476, l='Copy of Skylands (NEW)', x=6.50, y=256.00, z=6.50]]
	Chunk stats: ServerChunkCache: 445 Drop: 0
	Level seed: -4959463497117993340
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by Geethebluesky** [comment]
That was reported on the TF hub a while back: https://github.com/TeamTwilight/twilightforest/issues/517

What you could to is try one of their dev builds, the issue being closed on their end tells me it's probably solved.

**Comment by Nawor3565** [comment]
Yup, tried it on the dev build and it works fine. Thanks!
