### ISSUE TITLE
Hangs the server when creating the world

### ISSUE THREAD

**Issue by kellixon** [XCompWiz/Mystcraft-Issues#321]
MC 1.12.2.
Forge 14.23.5.2772
Mystcraft 0.13.7.01+147 mods.
Hangs the server when creating the world. A lot of spam in logs.
Full log ~720.000 lines. Below the line will spam the entire log after entering the created world.
`[14:42:35] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: java.lang.Exception: Stack trace
[14:42:35] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at java.lang.Thread.dumpStack(Unknown Source)
[14:42:35] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at micdoodle8.mods.galacticraft.api.prefab.world.gen.BiomeAdaptive.func_180622_a(BiomeAdaptive.java:231)
[14:42:35] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at com.xcompwiz.mystcraft.world.ChunkProviderMyst.replaceBlocksForBiome(ChunkProviderMyst.java:69)
[14:42:35] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at com.xcompwiz.mystcraft.world.ChunkProviderMyst.func_185932_a(ChunkProviderMyst.java:89)
[14:42:35] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143)
[14:42:35] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at com.xcompwiz.mystcraft.world.AgeController.expandChunkProfile(AgeController.java:348)
[14:42:35] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at com.xcompwiz.mystcraft.world.AgeController.updateProfiledInstability(AgeController.java:323)
[14:42:35] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at com.xcompwiz.mystcraft.world.AgeController.getInstabilityScore(AgeController.java:297)
[14:42:35] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at com.xcompwiz.mystcraft.instability.InstabilityController.validate(InstabilityController.java:84)
[14:42:35] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at com.xcompwiz.mystcraft.instability.InstabilityController.tick(InstabilityController.java:143)
[14:42:35] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at com.xcompwiz.mystcraft.world.AgeController.tickBlocksAndAmbiance(AgeController.java:599)
[14:42:35] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at com.xcompwiz.mystcraft.world.WorldProviderMyst.canDoLightning(WorldProviderMyst.java:322)
[14:42:35] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:403)
[14:42:35] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
[14:42:35] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
[14:42:35] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[14:42:35] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
[14:42:35] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[14:42:35] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at java.lang.Thread.run(Unknown Source)`

**Comment by HellFirePvP** [comment]
It's a stack printout on Galacticraft's side if the worldprovider is not what galacticraft expects.

https://github.com/micdoodle8/Galacticraft/blob/MC1.12/src/main/java/micdoodle8/mods/galacticraft/api/prefab/world/gen/BiomeAdaptive.java#L252

This log spam is not our fault.
