### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by ghost** [XCompWiz/Mystcraft-Issues#322]
Apologies if this is filed to the wrong place.

Forge 2768
Mystcraft 0.13.6.00 (I haven't updated to a newer version because 0.13.7.00 caused the pack to fail to start up, if this specific issue is fixed in a newer release point me to it)

I am getting this spammed in console endlessly, even after the server has been up for over half a day. It's causing world lag, is generating massive log files on the orders of half a GB or more, and I'm not sure what's going on. I haven't had this issue with another pack I was playing prior to making my own that had galcticraft, so I'm ignoring that as I think it's a red herring. I have attached the configs too in case it's something there.

`[06:27:12] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: java.lang.Exception: Stack trace
[06:27:12] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at java.lang.Thread.dumpStack(Unknown Source)
[06:27:12] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at micdoodle8.mods.galacticraft.api.prefab.world.gen.BiomeAdaptive.func_180622_a(BiomeAdaptive.java:231)
[06:27:12] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at com.xcompwiz.mystcraft.world.ChunkProviderMyst.replaceBlocksForBiome(ChunkProviderMyst.java:69)
[06:27:12] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at com.xcompwiz.mystcraft.world.ChunkProviderMyst.func_185932_a(ChunkProviderMyst.java:89)
[06:27:12] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.world.gen.ChunkProviderServer.redirect$generateChunk$zzf000(ChunkProviderServer.java:523)
[06:27:12] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143)
[06:27:12] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at com.xcompwiz.mystcraft.world.profiling.WorldProviderMystDummy.generateNextChunk(WorldProviderMystDummy.java:305)
[06:27:12] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at com.xcompwiz.mystcraft.world.profiling.InstabilityDataCalculator.stepChunkGeneration(InstabilityDataCalculator.java:376)
[06:27:12] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at com.xcompwiz.mystcraft.world.profiling.InstabilityDataCalculator.onServerTick(InstabilityDataCalculator.java:198)
[06:27:12] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2442_InstabilityDataCalculator_onServerTick_ServerTickEvent.invoke(.dynamic)
[06:27:12] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[06:27:12] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
[06:27:12] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
[06:27:12] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
[06:27:12] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[06:27:12] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at java.lang.Thread.run(Unknown Source)`

[mystcraft.zip](https://github.com/XCompWiz/Mystcraft-Issues/files/2529440/mystcraft.zip)

For a complete mod list: https://minecraft.curseforge.com/projects/continuity/files/2633082

**Comment by Veovis-Muaddib** [comment]
> Mystcraft 0.13.6.00 (I haven't updated to a newer version because 0.13.7.00 caused the pack to fail to start up, if this specific issue is fixed in a newer release point me to it)

Can you try updating to Forge 2770 or higher?

**Comment by ghost** [comment]
Unfortunately no. After the chaos that ensued with getting everything working with the recommended build (2768) after all the changes Lex did I'm not exactly keen on updating forge for a while.

**Comment by HellFirePvP** [comment]
Related to #321
