### ISSUE TITLE
[1.12.2] Server Crash When Entering a New Age

### ISSUE THREAD

**Issue by PascalSkylake** [XCompWiz/Mystcraft-Issues#369]
Managed to work the first time I used a book, after that no books worked

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.226.jar)
  ShutdownPatcher (mcef-1.12.2-0.9-coremod.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 8/7/19 8:00 PM
Description: Watching Server

java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
	at net.minecraft.world.World.func_189509_E(World.java:225)
	at net.minecraft.world.World.func_180501_a(World.java:320)
	at net.minecraft.world.gen.feature.WorldGenMinable.func_180709_b(WorldGenMinable.java:79)
	at net.minecraft.world.biome.BiomeDecorator.func_76795_a(BiomeDecorator.java:420)
	at net.minecraft.world.biome.BiomeDecorator.func_76797_b(BiomeDecorator.java:373)
	at net.minecraft.world.biome.BiomeDecorator.func_150513_a(BiomeDecorator.java:97)
	at net.minecraft.world.biome.BiomeDecorator.func_180292_a(BiomeDecorator.java:88)
	at net.minecraft.world.biome.Biome.func_180624_a(Biome.java:225)
	at net.minecraft.world.biome.BiomeSnow.func_180624_a(BiomeSnow.java:76)
	at com.xcompwiz.mystcraft.world.ChunkProviderMyst.func_185931_b(ChunkProviderMyst.java:142)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraft.world.World.func_175726_f(World.java:305)
	at net.minecraft.world.World.func_180495_p(World.java:911)
	at com.xcompwiz.mystcraft.world.gen.feature.WorldGenLakesAdv.doGeneration(WorldGenLakesAdv.java:75)
	at com.xcompwiz.mystcraft.world.gen.feature.WorldGeneratorAdv.func_180709_b(WorldGeneratorAdv.java:31)
	at com.xcompwiz.mystcraft.symbol.symbols.SymbolLakesSurface$Populator.populate(SymbolLakesSurface.java:55)
	at com.xcompwiz.mystcraft.world.AgeController.populate(AgeController.java:587)
	at com.xcompwiz.mystcraft.world.ChunkProviderMyst.func_185931_b(ChunkProviderMyst.java:149)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at com.xcompwiz.mystcraft.world.profiling.WorldProviderMystDummy.generateNextChunk(WorldProviderMystDummy.java:305)
	at com.xcompwiz.mystcraft.world.profiling.InstabilityDataCalculator.stepChunkGeneration(InstabilityDataCalculator.java:376)
	at com.xcompwiz.mystcraft.world.profiling.InstabilityDataCalculator.onServerTick(InstabilityDataCalculator.java:198)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_306_InstabilityDataCalculator_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server Watchdog
Stacktrace:
	at net.minecraft.world.World.func_189509_E(World.java:225)
	at net.minecraft.world.World.func_180501_a(World.java:320)
	at net.minecraft.world.gen.feature.WorldGenMinable.func_180709_b(WorldGenMinable.java:79)
	at net.minecraft.world.biome.BiomeDecorator.func_76795_a(BiomeDecorator.java:420)
	at net.minecraft.world.biome.BiomeDecorator.func_76797_b(BiomeDecorator.java:373)
	at net.minecraft.world.biome.BiomeDecorator.func_150513_a(BiomeDecorator.java:97)
	at net.minecraft.world.biome.BiomeDecorator.func_180292_a(BiomeDecorator.java:88)
	at net.minecraft.world.biome.Biome.func_180624_a(Biome.java:225)
	at net.minecraft.world.biome.BiomeSnow.func_180624_a(BiomeSnow.java:76)
	at com.xcompwiz.mystcraft.world.ChunkProviderMyst.func_185931_b(ChunkProviderMyst.java:142)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraft.world.World.func_175726_f(World.java:305)
	at net.minecraft.world.World.func_180495_p(World.java:911)
	at com.xcompwiz.mystcraft.world.gen.feature.WorldGenLakesAdv.doGeneration(WorldGenLakesAdv.java:75)
	at com.xcompwiz.mystcraft.world.gen.feature.WorldGeneratorAdv.func_180709_b(WorldGeneratorAdv.java:31)
	at com.xcompwiz.mystcraft.symbol.symbols.SymbolLakesSurface$Populator.populate(SymbolLakesSurface.java:55)
	at com.xcompwiz.mystcraft.world.AgeController.populate(AgeController.java:587)
	at com.xcompwiz.mystcraft.world.ChunkProviderMyst.func_185931_b(ChunkProviderMyst.java:149)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at com.xcompwiz.mystcraft.world.profiling.WorldProviderMystDummy.generateNextChunk(WorldProviderMystDummy.java:305)
	at com.xcompwiz.mystcraft.world.profiling.InstabilityDataCalculator.stepChunkGeneration(InstabilityDataCalculator.java:376)
	at com.xcompwiz.mystcraft.world.profiling.InstabilityDataCalculator.onServerTick(InstabilityDataCalculator.java:198)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_306_InstabilityDataCalculator_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)

-- Thread Dump --
Details:
	Threads: "Netty Server IO #8" Id=66 RUNNABLE (in native)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
	-  locked io.netty.channel.nio.SelectedSelectionKeySet@5cc0da0a
	-  locked java.util.Collections$UnmodifiableSet@52073fe2
	-  locked sun.nio.ch.WindowsSelectorImpl@5638b17a
	at sun.nio.ch.SelectorImpl.select(Unknown Source)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:732)
	...

"Netty Server IO #7" Id=62 RUNNABLE (in native)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
	-  locked io.netty.channel.nio.SelectedSelectionKeySet@133a35d9
	-  locked java.util.Collections$UnmodifiableSet@49f0ad3e
	-  locked sun.nio.ch.WindowsSelectorImpl@226363cd
	at sun.nio.ch.SelectorImpl.select(Unknown Source)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:732)
	...

"Netty Server IO #6" Id=61 RUNNABLE (in native)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
	-  locked io.netty.channel.nio.SelectedSelectionKeySet@3143a59a
	-  locked java.util.Collections$UnmodifiableSet@7315ca96
	-  locked sun.nio.ch.WindowsSelectorImpl@3fc01097
	at sun.nio.ch.SelectorImpl.select(Unknown Source)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:732)
	...

"Netty Server IO #5" Id=60 RUNNABLE (in native)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
	-  locked io.netty.channel.nio.SelectedSelectionKeySet@60471a9
	-  locked java.util.Collections$UnmodifiableSet@2a476b86
	-  locked sun.nio.ch.WindowsSelectorImpl@775b5522
	at sun.nio.ch.SelectorImpl.select(Unknown Source)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:732)
	...

"Netty Server IO #4" Id=56 RUNNABLE (in native)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
	-  locked io.netty.channel.nio.SelectedSelectionKeySet@48a0b7f6
	-  locked java.util.Collections$UnmodifiableSet@6d0c1e72
	-  locked sun.nio.ch.WindowsSelectorImpl@7c06430e
	at sun.nio.ch.SelectorImpl.select(Unknown Source)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:732)
	...

"Netty Server IO #3" Id=55 RUNNABLE (in native)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
	-  locked io.netty.channel.nio.SelectedSelectionKeySet@5159ebe9
	-  locked java.util.Collections$UnmodifiableSet@1c8bf933
	-  locked sun.nio.ch.WindowsSelectorImpl@11f99b5e
	at sun.nio.ch.SelectorImpl.select(Unknown Source)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:732)
	...

"Netty Server IO #2" Id=54 RUNNABLE (in native)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
	-  locked io.netty.channel.nio.SelectedSelectionKeySet@5f29b45c
	-  locked java.util.Collections$UnmodifiableSet@41b10af3
	-  locked sun.nio.ch.WindowsSelectorImpl@2302197
	at sun.nio.ch.SelectorImpl.select(Unknown Source)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:732)
	...

"threadDeathWatcher-2-1" Id=53 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:152)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Unknown Source)

"Netty Server IO #1" Id=52 RUNNABLE (in native)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
	-  locked io.netty.channel.nio.SelectedSelectionKeySet@5fce79e4
	-  locked java.util.Collections$UnmodifiableSet@4dd7ad15
	-  locked sun.nio.ch.WindowsSelectorImpl@4f8c0ce
	at sun.nio.ch.SelectorImpl.select(Unknown Source)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:732)
	...

"File IO Thread" Id=49 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:51)
	at net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:30)
	at java.lang.Thread.run(Unknown Source)

"Thread-6" Id=44 TIMED_WAITING on com.xcompwiz.mystcraft.world.profiling.ChunkProfilerManager@7c7655f
	at java.lang.Object.wait(Native Method)
	-  waiting on com.xcompwiz.mystcraft.world.profiling.ChunkProfilerManager@7c7655f
	at com.xcompwiz.mystcraft.world.profiling.ChunkProfilerManager.run(ChunkProfilerManager.java:87)

"Server Watchdog" Id=43 RUNNABLE
	at sun.management.ThreadImpl.dumpThreads0(Native Method)
	at sun.management.ThreadImpl.dumpAllThreads(Unknown Source)
	at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:45)
	at java.lang.Thread.run(Unknown Source)

"MiniServServer" Id=42 RUNNABLE (in native)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
	-  locked sun.nio.ch.Util$3@2bea3d1a
	-  locked java.util.Collections$UnmodifiableSet@5b258277
	-  locked sun.nio.ch.WindowsSelectorImpl@1919c76d
	at sun.nio.ch.SelectorImpl.select(Unknown Source)
	at net.montoyo.wd.miniserv.server.Server.loopUnsafe(Server.java:138)
	at net.montoyo.wd.miniserv.server.Server.run(Server.java:114)
	...

"Java2D Disposer" Id=41 WAITING on java.lang.ref.ReferenceQueue$Lock@25c8a48c
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@25c8a48c
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at sun.java2d.Disposer.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

"Netty Server IO #0" Id=40 RUNNABLE (in native)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
	-  locked io.netty.channel.nio.SelectedSelectionKeySet@5fb05fc2
	-  locked java.util.Collections$UnmodifiableSet@28f14879
	-  locked sun.nio.ch.WindowsSelectorImpl@7f84d0a5
	at sun.nio.ch.SelectorImpl.select(Unknown Source)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:732)
	...

"JLine terminal non blocking reader thread" Id=24 TIMED_WAITING on org.jline.utils.NonBlockingReader@1f88e71d
	at java.lang.Object.wait(Native Method)
	-  waiting on org.jline.utils.NonBlockingReader@1f88e71d
	at org.jline.utils.NonBlockingReader.run(NonBlockingReader.java:257)
	at java.lang.Thread.run(Unknown Source)

"Server console handler" Id=23 RUNNABLE
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	...

"DestroyJavaVM" Id=22 RUNNABLE

"Server thread" Id=20 RUNNABLE
	at net.minecraft.world.World.func_189509_E(World.java:225)
	at net.minecraft.world.World.func_180501_a(World.java:320)
	at net.minecraft.world.gen.feature.WorldGenMinable.func_180709_b(WorldGenMinable.java:79)
	at net.minecraft.world.biome.BiomeDecorator.func_76795_a(BiomeDecorator.java:420)
	at net.minecraft.world.biome.BiomeDecorator.func_76797_b(BiomeDecorator.java:373)
	at net.minecraft.world.biome.BiomeDecorator.func_150513_a(BiomeDecorator.java:97)
	at net.minecraft.world.biome.BiomeDecorator.func_180292_a(BiomeDecorator.java:88)
	at net.minecraft.world.biome.Biome.func_180624_a(Biome.java:225)
	...

"Server Infinisleeper" Id=19 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:82)

"Snooper Timer" Id=18 TIMED_WAITING on java.util.TaskQueue@600bdfcb
	at java.lang.Object.wait(Native Method)
	-  waiting on java.util.TaskQueue@600bdfcb
	at java.util.TimerThread.mainLoop(Unknown Source)
	at java.util.TimerThread.run(Unknown Source)

"WindowsStreamPump" Id=14 RUNNABLE
	at com.sun.jna.Native.invokeVoid(Native Method)
	at com.sun.jna.Function.invoke(Function.java:408)
	at com.sun.jna.Function.invoke(Function.java:354)
	at com.sun.jna.Library$Handler.invoke(Library.java:244)
	at org.jline.terminal.impl.jna.win.$Proxy23.ReadConsoleInput(Unknown Source)
	at org.jline.terminal.impl.jna.win.JnaWinSysTerminal.readConsoleInput(JnaWinSysTerminal.java:130)
	at org.jline.terminal.impl.jna.win.JnaWinSysTerminal.processConsoleInput(JnaWinSysTerminal.java:65)
	at org.jline.terminal.impl.AbstractWindowsTerminal.pump(AbstractWindowsTerminal.java:400)
	...

"Attach Listener" Id=5 RUNNABLE

"Signal Dispatcher" Id=4 RUNNABLE

"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@39d32a97
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@39d32a97
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)

"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@613b82bf
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.Reference$Lock@613b82bf
	at java.lang.Object.wait(Unknown Source)
	at java.lang.ref.Reference.tryHandlePending(Unknown Source)
	at java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)

Stacktrace:
	at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:62)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2913233112 bytes (2778 MB) / 3846176768 bytes (3668 MB) up to 9544663040 bytes (9102 MB)
	JVM Flags: 2 total; -Xmx10240M -Xms1024M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 28 mods loaded, 28 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version           | Source                                           | Signature                                |
	|:------ |:------------------- |:----------------- |:------------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2            | minecraft.jar                                    | None                                     |
	| LCHIJA | mcp                 | 9.42              | minecraft.jar                                    | None                                     |
	| LCHIJA | FML                 | 8.0.99.99         | sever.jar                                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2838      | sever.jar                                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | micdoodlecore       |                   | minecraft.jar                                    | None                                     |
	| LCHIJA | biomesoplenty       | 7.0.1.2427        | BiomesOPlenty-1.12.2-7.0.1.2427-universal.jar    | None                                     |
	| LCHIJA | buildcraftlib       | 7.99.24.2         | buildcraft-all-7.99.24.2.jar                     | None                                     |
	| LCHIJA | buildcraftcore      | 7.99.24.2         | buildcraft-all-7.99.24.2.jar                     | None                                     |
	| LCHIJA | buildcraftbuilders  | 7.99.24.2         | buildcraft-all-7.99.24.2.jar                     | None                                     |
	| LCHIJA | buildcrafttransport | 7.99.24.2         | buildcraft-all-7.99.24.2.jar                     | None                                     |
	| LCHIJA | buildcraftsilicon   | 7.99.24.2         | buildcraft-all-7.99.24.2.jar                     | None                                     |
	| LCHIJA | buildcraftcompat    | 7.99.24.2         | buildcraft-all-7.99.24.2.jar                     | None                                     |
	| LCHIJA | buildcraftenergy    | 7.99.24.2         | buildcraft-all-7.99.24.2.jar                     | None                                     |
	| LCHIJA | buildcraftfactory   | 7.99.24.2         | buildcraft-all-7.99.24.2.jar                     | None                                     |
	| LCHIJA | buildcraftrobotics  | 7.99.24.2         | buildcraft-all-7.99.24.2.jar                     | None                                     |
	| LCHIJA | codechickenlib      | 3.2.2.353         | CodeChickenLib-1.12.2.jar                        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | mantle              | 1.12-1.3.3.55     | Mantle-Mod-1.12.2.jar                            | None                                     |
	| LCHIJA | jei                 | 4.15.0.287        | jei_1.12.2-4.15.0.287.jar                        | None                                     |
	| LCHIJA | tconstruct          | 1.12.2-2.12.0.115 | Tinkers-Construct-Mod-1.12.2.jar                 | None                                     |
	| LCHIJA | galacticraftcore    | 4.0.2.226         | GalacticraftCore-1.12.2-4.0.2.226.jar            | None                                     |
	| LCHIJA | galacticraftplanets | 4.0.2.226         | Galacticraft-Planets-1.12.2-4.0.2.226.jar        | None                                     |
	| LCHIJA | mjrlegendslib       | 1.12.2-1.1.8      | MJRLegendsLib-1.12.2-1.1.8.jar                   | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA | extraplanets        | 1.12.2-0.5.5      | Extra-Planets-Mod-1.12.2.jar                     | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA | mcef                | 0.9               | Minecraft-Chromium-Embedded-Framework-1.12.2.jar | None                                     |
	| LCHIJA | mystcraft           | 0.13.7.02         | Mystcraft-Mod-1.12.2.jar                         | None                                     |
	| LCHIJA | nei                 | 2.4.1             | Not-Enough-Items-1.12.2-Recommended.jar          | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | harvestcraft        | 1.12.2zb          | Pam's+HarvestCraft+1.12.2ze.jar                  | None                                     |
	| LCHIJA | webdisplays         | 1.0               | Web-Displays-Mod-1.12.2.jar                      | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.226.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
ShutdownPatcher (mcef-1.12.2-0.9-coremod.jar)
  net.montoyo.mcef.coremod.ShutdownPatcher
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by XCompWiz** [comment]
It's apparently a server hang and there's a mod that's killing it when it takes too long (ServerHangWatchdog).
It might be that a dimension is failing to generate quickly enough. Possibly due to an interaction with another mod.
See [Bug Reporting Best Practices](https://github.com/XCompWiz/Mystcraft-Issues/wiki/Bug-Reporting-Best-Practices) for some possible steps to help determine the issue.
