### ISSUE TITLE
Mystcraft crashing server with SpongeForge

### ISSUE THREAD

**Issue by ben21121** [XCompWiz/Mystcraft-Issues#388]
net.minecraft.world.WorldProviderSurface cannot be cast to com.xcompwiz.mystcraft.world.profiling.WorldProviderMystDummy
    at com.xcompwiz.mystcraft.world.profiling.InstabilityDataCalculator.stepChunkGeneration(InstabilityDataCalculator.java:376)
    at com.xcompwiz.mystcraft.world.profiling.InstabilityDataCalculator.onServerTick(InstabilityDataCalculator.java:198)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2172_InstabilityDataCalculator_onServerTick_ServerTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:756)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:706)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:712)
    at net.minecraft.server.MinecraftS

With the Mystcraft mod installed the server will load up right until the world is finished loading and then crash with this error, without SpongeForge this doesn't happen but of course i need that for my plugins so for the meantime i have deleted Mystcraft from the server and it works fine so my players can get on,
Are you aware of this conflict? and is there anything i can do in the configs?
I would like to have myscraft installed as i find the /tpx command and a few other features useful.

**Comment by no-identd** [comment]
#379 ?
