### ISSUE TITLE
Mystcraft crashes upon entering any age. 1.12.2

### ISSUE THREAD

**Issue by hypercanetornado** [XCompWiz/Mystcraft-Issues#403]
Any help you guys can provide would be wonderful!

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  LevelUpCore (levelup2-1.5.8.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  HCASM (HammerLib-1.12.2-2.0.6.23.jar)
  ApotheosisCore (Apotheosis-1.12.2-1.10.2.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 7/6/21 11:52 AM
Description: Exception while ticking a block

java.lang.NullPointerException: Exception while ticking a block
	at net.minecraft.block.BlockFire.func_180650_b(BlockFire.java:217)
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:737)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.block.BlockFire.func_180650_b(BlockFire.java:217)

-- Block being ticked --
Details:
	Block: minecraft:fire[age=7,east=false,north=false,south=false,up=false,west=false]
	Block location: World: (-102,23,233), Chunk: (at 10,1,9 in -7,14; contains blocks -112,0,224 to -97,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:737)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223)

-- Affected level --
Details:
	Level name: I O U
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 526 Drop: 254
	Level seed: 4042180590432931947
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {"diamondSize":8,"lapisCenterHeight":16,"lavaLakeChance":80,"redstoneMaxHeight":16,"diamondMaxHeight":16,"coalMaxHeight":128,"coalMinHeight":0,"seaLevel":63,"graniteCount":10,"riverSize":4,"gravelMinHeight":0,"graniteSize":33,"redstoneSize":8,"fixedBiome":-1,"waterLakeChance":4,"dioriteMinHeight":0,"andesiteCount":10,"graniteMaxHeight":80,"redstoneMinHeight":0,"lapisSize":7,"dirtCount":10,"ironMinHeight":0,"dioriteMaxHeight":80,"coalCount":20,"gravelCount":8,"coalSize":17,"gravelSize":33,"ironMaxHeight":64,"lapisSpread":16,"dioriteCount":10,"andesiteSize":33,"biomeSize":4,"graniteMinHeight":0,"goldCount":2,"diamondCount":1,"dirtSize":33,"gravelMaxHeight":256,"goldSize":9,"ironCount":20,"diamondMinHeight":0,"ironSize":9,"redstoneCount":8,"andesiteMinHeight":0,"dioriteSize":33,"goldMaxHeight":32,"dungeonChance":8,"andesiteMaxHeight":80,"dirtMinHeight":0,"lapisCount":1,"goldMinHeight":0,"dirtMaxHeight":256,"lowerLimitScale":512.0,"biomeDepthOffset":0.0,"upperLimitScale":512.0,"heightScale":684.412,"biomeScaleWeight":1.0,"biomeDepthWeight":1.0,"mainNoiseScaleZ":80.0,"mainNoiseScaleY":160.0,"depthNoiseScaleX":200.0,"mainNoiseScaleX":80.0,"baseSize":8.5,"depthNoiseScaleZ":200.0,"stretchY":12.0,"depthNoiseScaleExponent":0.5,"biomeScaleOffset":0.0,"coordinateScale":684.412,"useStrongholds":true,"useMineShafts":true,"useTemples":true,"useLavaOceans":false,"useCaves":true,"useWaterLakes":true,"useLavaLakes":true,"useMonuments":true,"useRavines":true,"useDungeons":true,"useVillages":true}
	Level spawn location: World: (-104,64,256), Chunk: (at 8,4,0 in -7,16; contains blocks -112,0,256 to -97,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1251 game time, 1251 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 173582 (now: false), thunder time: 140864 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3794352496 bytes (3618 MB) / 10569646080 bytes (10080 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 72, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_G5 87 mods loaded, 87 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version                  | Source                                             | Signature                                |
	|:------ |:--------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2                   | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp                   | 9.42                     | minecraft.jar                                      | None                                     |
	| LCHIJA | FML                   | 8.0.99.99                | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
	| LCHIJA | forge                 | 14.23.5.2847             | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
	| LCHIJA | micdoodlecore         |                          | minecraft.jar                                      | None                                     |
	| LCHIJA | openmodscore          | 0.12.2                   | minecraft.jar                                      | None                                     |
	| LCHIJA | actuallyadditions     | 1.12.2-r152              | ActuallyAdditions-1.12.2-r152.jar                  | None                                     |
	| LCHIJA | mantle                | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                           | None                                     |
	| LCHIJA | inspirations          | 1.12.2-0.2.9             | Inspirations-1.12.2-0.2.9.jar                      | None                                     |
	| LCHIJA | placebo               | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                           | None                                     |
	| LCHIJA | apotheosis            | 1.10.2                   | Apotheosis-1.12.2-1.10.2.jar                       | None                                     |
	| LCHIJA | appliedenergistics2   | rv6-stable-7             | appliedenergistics2-rv6-stable-7.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | jei                   | 4.15.0.281               | jei_1.12.2-4.15.0.281.jar                          | None                                     |
	| LCHIJA | quark                 | r1.6-179                 | Quark-r1.6-179.jar                                 | None                                     |
	| LCHIJA | autoreglib            | 1.3-32                   | AutoRegLib-1.3-32.jar                              | None                                     |
	| LCHIJA | codechickenlib        | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | avaritia              | 3.3.0                    | Avaritia-1.12.2-3.3.0.37-universal.jar             | None                                     |
	| LCHIJA | forgelin              | 1.8.4                    | Forgelin-1.8.4.jar                                 | None                                     |
	| LCHIJA | betterportals         | 0.3.7.7                  | betterportals-0.3.7.7.jar                          | None                                     |
	| LCHIJA | bibliocraft           | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
	| LCHIJA | redstoneflux          | 2.1.1                    | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
	| LCHIJA | brandonscore          | 2.4.19                   | BrandonsCore-1.12.2-2.4.19.214-universal.jar       | None                                     |
	| LCHIJA | buildcraftlib         | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCHIJA | buildcraftcore        | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCHIJA | buildcraftbuilders    | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCHIJA | buildcrafttransport   | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCHIJA | buildcraftsilicon     | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCHIJA | buildcraftcompat      | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCHIJA | buildcraftenergy      | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCHIJA | buildcraftfactory     | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCHIJA | buildcraftrobotics    | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCHIJA | chickenchunks         | 2.4.2.74                 | ChickenChunks-1.12.2-2.4.2.74-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | chickens              | 6.0.4                    | chickens-6.0.4.jar                                 | None                                     |
	| LCHIJA | cofhcore              | 4.6.6                    | CoFHCore-1.12.2-4.6.6.1-universal.jar              | None                                     |
	| LCHIJA | cofhworld             | 1.4.0                    | CoFHWorld-1.12.2-1.4.0.1-universal.jar             | None                                     |
	| LCHIJA | twilightforest        | 3.11.1021                | twilightforest-1.12.2-3.11.1021-universal.jar      | None                                     |
	| LCHIJA | tconstruct            | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                   | None                                     |
	| LCHIJA | conarm                | 1.2.5.10                 | conarm-1.12.2-1.2.5.10.jar                         | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
	| LCHIJA | extendedrenderer      | v1.0                     | coroutil-1.12.1-1.2.37.jar                         | None                                     |
	| LCHIJA | coroutil              | 1.12.1-1.2.37            | coroutil-1.12.1-1.2.37.jar                         | None                                     |
	| LCHIJA | configmod             | v1.0                     | coroutil-1.12.1-1.2.37.jar                         | None                                     |
	| LCHIJA | cucumber              | 1.1.3                    | Cucumber-1.12.2-1.1.3.jar                          | None                                     |
	| LCHIJA | thermalfoundation     | 2.6.7                    | ThermalFoundation-1.12.2-2.6.7.1-universal (1).jar | None                                     |
	| LCHIJA | deepmoblearning       | 1.12.2-2.5.4             | deepmoblearning-1.12.2-2.5.4-universal.jar         | None                                     |
	| LCHIJA | dimdoors              | 1.12.2-3.1.2+UNOFFICIAL  | DimensionalDoors-1.12.2-3.1.2-UNOFFICIAL.jar       | None                                     |
	| LCHIJA | draconicevolution     | 2.3.27                   | Draconic-Evolution-1.12.2-2.3.27.353-universal.jar | None                                     |
	| LCHIJA | energyconverters      | 1.3.7.30                 | energyconverters_1.12.2-1.3.7.30.jar               | None                                     |
	| LCHIJA | exnihilocreatio       | 1.12.2-0.4.7.2           | exnihilocreatio-1.12.2-0.4.7.2.jar                 | None                                     |
	| LCHIJA | galacticraftcore      | 4.0.2.280                | GalacticraftCore-1.12.2-4.0.2.280.jar              | None                                     |
	| LCHIJA | galacticraftplanets   | 4.0.2.280                | Galacticraft-Planets-1.12.2-4.0.2.280.jar          | None                                     |
	| LCHIJA | mjrlegendslib         | 1.12.2-1.2.1             | MJRLegendsLib-1.12.2-1.2.1.jar                     | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA | extraplanets          | 1.12.2-0.7.3             | ExtraPlanets-1.12.2-0.7.3.jar                      | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA | extrautils2           | 1.0                      | extrautils2-1.12-1.9.9.jar                         | None                                     |
	| LCHIJA | zerocore              | 1.12.2-0.1.2.9           | zerocore-1.12.2-0.1.2.9.jar                        | None                                     |
	| LCHIJA | bigreactors           | 1.12.2-0.4.5.68          | ExtremeReactors-1.12.2-0.4.5.68.jar                | None                                     |
	| LCHIJA | forgemultipartcbe     | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | microblockcbe         | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | None                                     |
	| LCHIJA | minecraftmultipartcbe | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | None                                     |
	| LCHIJA | hammercore            | 2.0.6.23                 | HammerLib-1.12.2-2.0.6.23.jar                      | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCHIJA | waila                 | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| LCHIJA | journeymap            | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                        | None                                     |
	| LCHIJA | justenoughreactors    | 1.1.3.61                 | JustEnoughReactors-1.12.2-1.1.3.61.jar             | 2238d4a92d81ab407741a2fdb741cebddfeacba6 |
	| LCHIJA | jeresources           | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar            | None                                     |
	| LCHIJA | levelup2              | ${version}               | levelup2-1.5.8.jar                                 | None                                     |
	| LCHIJA | malisiscore           | 1.12.2-6.5.1-SNAPSHOT    | malisiscore-1.12.2-6.5.1.jar                       | None                                     |
	| LCHIJA | malisisdoors          | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                      | None                                     |
	| LCHIJA | mcjtylib_ng           | 3.5.4                    | mcjtylib-1.12-3.5.4.jar                            | None                                     |
	| LCHIJA | mekanism              | 1.12.2-9.8.3.390         | Mekanism-1.12.2-9.8.3.390.jar                      | None                                     |
	| LCHIJA | mekanismgenerators    | 1.12.2-9.8.3.390         | MekanismGenerators-1.12.2-9.8.3.390.jar            | None                                     |
	| LCHIJA | mekanismtools         | 1.12.2-9.8.3.390         | MekanismTools-1.12.2-9.8.3.390.jar                 | None                                     |
	| LCHIJA | mob_grinding_utils    | 0.3.13                   | MobGrindingUtils-0.3.13.jar                        | None                                     |
	| LCHIJA | morecauldrons         | 1.4.6                    | More-Cauldrons-1.4.6.jar                           | None                                     |
	| LCHIJA | morechickens          | 3.1.0                    | morechickens-1.12.2-3.1.0.jar                      | None                                     |
	| LCHIJA | mystcraft             | 0.13.7.06                | mystcraft-1.12.2-0.13.7.06.jar                     | None                                     |
	| LCHIJA | norecipebook          | 1.2.1                    | noRecipeBook_v1.2.2formc1.12.2.jar                 | None                                     |
	| LCHIJA | notenoughwands        | 1.8.1                    | notenoughwands-1.12-1.8.1.jar                      | None                                     |
	| LCHIJA | openmods              | 0.12.2                   | OpenModsLib-1.12.2-0.12.2.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | openblocks            | 1.8.1                    | OpenBlocks-1.12.2-1.8.1.jar                        | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | oreexcavation         | 1.4.140                  | OreExcavation-1.4.140.jar                          | None                                     |
	| LCHIJA | portality             | 1.0-SNAPSHOT             | portality-1.12.2-1.2.3-15.jar                      | None                                     |
	| LCHIJA | rftools               | 7.73                     | rftools-1.12-7.73.jar                              | None                                     |
	| LCHIJA | roost                 | 2.0.10                   | roost-1.12.2-2.0.10.jar                            | None                                     |
	| LCHIJA | thermalexpansion      | 5.5.7                    | ThermalExpansion-1.12.2-5.5.7.1-universal.jar      | None                                     |
	| LCHIJA | tcomplement           | 1.12.2-0.4.2             | Tinkers-Complement-Mod-1.12.2.jar                  | None                                     |
	| LCHIJA | tinkertoolleveling    | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                | None                                     |
	| LCHIJA | tp                    | 3.2.34                   | tinyprogressions-1.12.2-3.3.34-Release.jar         | None                                     |
	| LCHIJA | translocators         | 2.5.2.81                 | Translocators-1.12.2-2.5.2.81-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.4.jar)
  
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
LevelUpCore (levelup2-1.5.8.jar)
  
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
HCASM (HammerLib-1.12.2-2.0.6.23.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
ApotheosisCore (Apotheosis-1.12.2-1.10.2.jar)
  shadows.ApotheosisTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Pulsar/inspirations loaded Pulses: 
		- InspirationsShared (Enabled/Forced)
		- InspirationsBuilding (Enabled/Not Forced)
		- InspirationsUtility (Enabled/Not Forced)
		- InspirationsTools (Enabled/Not Forced)
		- InspirationsRecipes (Enabled/Not Forced)
		- InspirationsTweaks (Enabled/Not Forced)
		- InspirationsShared (Enabled/Forced)
		- WailaPlugin (Enabled/Not Forced)
		- TwilightForestPlugin (Enabled/Not Forced)

	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)
		- quarkIntegration (Enabled/Not Forced)

	HammerCore Debug Information: 
		Dependent Mods: None.

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleMelter (Enabled/Not Forced)
		- ModuleArmor (Enabled/Not Forced)
		- ModuleSteelworks (Enabled/Not Forced)
		- ExNihiloPlugin (Enabled/Not Forced)
		- ToolLevelingPlugin (Enabled/Not Forced)
		- Oredict (Enabled/Forced)

	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:ON, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [GCEntityPlayerMP['HypercaneTornado'/9493, l='I O U', x=28.50, y=87.00, z=-28.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 12
	Mipmaps: 1
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 441.87
	OpenGlRenderer: GeForce GTX 960M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by Xplodin** [comment]
Change server.properties max-tick-time to -1

Should stop the crashing when entering an age
