### ISSUE TITLE
Crash with MystCraft 0.11.12.00 and Witchery 0.24.1

### ISSUE THREAD

**Issue by AlexPlus117** [XCompWiz/Mystcraft-Issues#99]
I'm using these mods in my modpack and before upgrading your mod from 0.11.11.00 to 0.11.12.00 it had worked fine, but after having upgraded MystCraft I had a crash with Witchery 0.24.1 installed. This is the crash-report:

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.entity.EntityClientPlayerMP.func_71016_p(SourceFile:204)
	at com.emoniph.witchery.common.Shapeshift.initCurrentShift(Shapeshift.java:179)
	at com.emoniph.witchery.common.GenericEvents.onEntityJoinWorld(GenericEvents.java:190)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1738_GenericEvents_onEntityJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.world.World.func_72838_d(World.java:1334)
	at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:159)
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2231)
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2146)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:240)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.entity.EntityClientPlayerMP.func_71016_p(SourceFile:204)
	at com.emoniph.witchery.common.Shapeshift.initCurrentShift(Shapeshift.java:179)
	at com.emoniph.witchery.common.GenericEvents.onEntityJoinWorld(GenericEvents.java:190)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1738_GenericEvents_onEntityJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.world.World.func_72838_d(World.java:1334)
	at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:159)
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2231)
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2146)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:240)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

**Comment by XCompWiz** [comment]
This is actually this issue: #101 
Try disabling the bspkrsCore main menu mobs and you should be fine. :)
